// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToAvansToGo.Infrastructure.Data;

#nullable disable

namespace ToAvansToGo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261009123315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.Property<int>("PackagesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("PackagesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("PackageProducts", (string)null);
                });

            modelBuilder.Entity("ToAvansToGo.Domain.Entities.Canteen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HasHotMeals")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("City", "Location")
                        .IsUnique();

                    b.ToTable("Canteens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Breda",
                            HasHotMeals = true,
                            Location = "LA Gebouw"
                        },
                        new
                        {
                            Id = 2,
                            City = "Tilburg",
                            HasHotMeals = true,
                            Location = "Hoofdkantine"
                        },
                        new
                        {
                            Id = 3,
                            City = "Denbosch",
                            HasHotMeals = false,
                            Location = "Kantine Onderwijsboulevard"
                        },
                        new
                        {
                            Id = 4,
                            City = "Breda",
                            HasHotMeals = true,
                            Location = "LD Gebouw"
                        });
                });

            modelBuilder.Entity("ToAvansToGo.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanteenId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CanteenId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanteenId = 1,
                            EmployeeNumber = 1001,
                            Name = "Piet Bakker"
                        },
                        new
                        {
                            Id = 2,
                            CanteenId = 2,
                            EmployeeNumber = 1002,
                            Name = "Sanne Smit"
                        });
                });

            modelBuilder.Entity("ToAvansToGo.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AvailableTill")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is18Plus")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PickUpLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickUpTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ReservedById")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfMeal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PickUpLocationId");

                    b.HasIndex("ReservedById");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("ToAvansToGo.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasAlcohol")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasAlcohol = false,
                            Name = "Broodje kaas",
                            Picture = "broodje-kaas.jpg"
                        },
                        new
                        {
                            Id = 2,
                            HasAlcohol = false,
                            Name = "Tosti ham-kaas",
                            Picture = "tosti.jpg"
                        },
                        new
                        {
                            Id = 3,
                            HasAlcohol = false,
                            Name = "Soep van de dag",
                            Picture = "soep.jpg"
                        },
                        new
                        {
                            Id = 4,
                            HasAlcohol = true,
                            Name = "Fles bier",
                            Picture = "bier.jpg"
                        },
                        new
                        {
                            Id = 5,
                            HasAlcohol = false,
                            Name = "Cola",
                            Picture = "cola.jpg"
                        },
                        new
                        {
                            Id = 6,
                            HasAlcohol = false,
                            Name = "Red Bull",
                            Picture = "redbull.jpg"
                        },
                        new
                        {
                            Id = 7,
                            HasAlcohol = false,
                            Name = "Croissant",
                            Picture = "croissant.jpg"
                        });
                });

            modelBuilder.Entity("ToAvansToGo.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("StudyCity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2003, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jan.jansen@student.avans.nl",
                            Name = "Jan Jansen",
                            PhoneNumber = "0612345678",
                            StudentNumber = 2200001,
                            StudyCity = "Breda"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2008, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lisa.devries@student.avans.nl",
                            Name = "Lisa de Vries",
                            PhoneNumber = "0687654321",
                            StudentNumber = 2200002,
                            StudyCity = "Tilburg"
                        });
                });

            modelBuilder.Entity("PackageProduct", b =>
                {
                    b.HasOne("ToAvansToGo.Domain.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToAvansToGo.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToAvansToGo.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ToAvansToGo.Domain.Entities.Canteen", "Location")
                        .WithMany()
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ToAvansToGo.Domain.Entities.Package", b =>
                {
                    b.HasOne("ToAvansToGo.Domain.Entities.Canteen", "PickUpLocation")
                        .WithMany()
                        .HasForeignKey("PickUpLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ToAvansToGo.Domain.Entities.Student", "ReservedBy")
                        .WithMany()
                        .HasForeignKey("ReservedById");

                    b.Navigation("PickUpLocation");

                    b.Navigation("ReservedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
